- name: Install Certbot and dependencies
  apt:
    name: certbot
    state: present

- name: Obtain SSL certificates using Certbot
  shell: certbot certonly --standalone -d {{ domain_name }} --non-interactive --agree-tos --email {{ email }}
  args:
    creates: "{{ssl_cert_path}}"
