- name: Create WordPress directory
  file:
    path: /var/www/html/
    state: directory

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ wordpress_path }}"
    remote_src: yes

- name: set permissions for files
  command: >
    sudo find /var/www/html/wordpress -type f -exec chmod 644 {} \;

- name: Set permissions for directories
  command: >
    sudo find /var/www/html/wordpress -type d -exec chmod 755 {} \;


- name: Delete wp-config-sample.php
  ansible.builtin.file:
    path: /var/www/html/wordpress/wp-config-sample.php
    state: absent

- name: Set up wp-config.php
  template:
    src: "wp-config.php.j2"
    dest: "/var/www/html/wordpress/wp-config.php"
    owner: www-data
    group: www-data
    mode: '0644'

- name: Remove downloaded WordPress archive
  file:
    path: /tmp/latest.tar.gz
    state: absent
